### ISSUE TITLE
Check for dbmigrate > migrator changes

### ISSUE THREAD

**Issue by chapmandu** [chapmandu/UpgradeAdvisor#6]
- [ ] Check for `db/migrate` > `migrator/migrations`
- [ ] Check for `db/sql` > `migrator/sql`
- [ ] Check table `schemainfo` > `migrations`

**Comment by neokoenig** [comment]
`schemainfo > migrationversions`
(so as not to clash with ducks).

**Comment by chapmandu** [comment]
Closed via 3b16960eb601cd8eb33bc5f73e63331d972a9f60
